pwr <- read.table("household_power_consumption.txt",header = TRUE, sep = ";",as.is = c(3,4,5,6)) 
pwr <- subset(pwr,pwr$Date == "1/2/2007" | pwr$Date == "2/2/2007")
time2 <- paste(pwr$Date,pwr$Time)
time2   <- strptime(time2, format = "%d/%m/%Y  %H:%M:%S")
pwr$Global_active_power <- as.numeric(pwr$Global_active_power)
pwr$Global_reactive_power <- as.numeric(pwr$Global_reactive_power)
pwr$Voltage <- as.numeric(pwr$Voltage)
pwr <- cbind(pwr,time2)
png("Plot02.png", width = 480, height = 480)
plot(x = pwr$time2, y = pwr$Global_active_power, type = "l", main = "", xlab = "", ylab = "Global Active Power (Kilowats)")